import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";
import NavBar from "./components/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className="flex flex-col items-center justify-center w-full">
          <NavBar />
          {children}
        </body>
      </SessionWrapper>
    </html>
  );
}
